### ISSUE TITLE
New cookie is not set and provide ability to clear cookies

### ISSUE THREAD

**Issue by anandanand84** [Huachao/vscode-restclient#117]
- VSCode Version:
- OS Version: macOS Sierra version 10.12.5
- REST Client Version: 0.15.2

If a new cookie is returned from set-cookie header, it is not used, still old cookie is used for subsequent request. Also provide a way to clear cookies.

**Comment by Huachao** [comment]
@anandanand84 do you mean if the cookie with new value is returned from server, the subsequent requests don't use this new cookie value. It seems that I can't repro this, can you show me your response, and the cookie.json file (which is the file cookie jar) in `~/.rest-client/cookie.json`.

**Comment by anandanand84** [comment]
@Huachao my bad it does sets cookie if there is a new cookie sent.

sorry!

**Comment by GeorgeXc** [comment]
We need a command to clear the cookie.

**Comment by gregorwolf** [comment]
Hi @GeorgeXc, you can simply delete ~/.rest-client/cookie.json and restart VS Code.

**Comment by negstek** [comment]
restarting vscode every time is not an option, a command to clear the cache would be appreciated

**Comment by aeddie-zapidhire** [comment]
> Note to self, `rest-client.rememberCookiesForSubsequentRequests` can be set to `false` if needed.

**Comment by jeankueo2** [comment]
I meet the same issue. I am using to user/password (for different roles) set to test against one host. Because we enabled CSRF token, i need "rest-client.rememberCookiesForSubsequentRequests" to be true. And i save the host/user/password combination as two system variable.
Now the problem is, after a get-csrf, post call of user 1,
I trigger a get-csrf call of user 2, in this case i do not get set-cookies back, and cookies.json file is not updated. So unless i delete cookie file and restart vs code, i cannot smoothly switch between user 1 and user 2.
