### ISSUE TITLE
code block folder/unfolder feature in .http/.rest file

### ISSUE THREAD

**Issue by hyperpc** [Huachao/vscode-restclient#139]
A very helpful extension on vs code, thanks~

Here suggest to add a new feature:
be able to folder/unfolder code block.

For example, many API requests existing in one .http/.rest file, if each request can unfolder into one line, it will be very helpful. Or give a tag, like #region/#endregion in csharp.

Thanks again.

**Comment by Huachao** [comment]
@hyperpc nice suggestion, and I will publish this feature in next release, thanks 😄

**Comment by Huachao** [comment]
@hyperpc you can try the latest version **0.16.1** to verify.

**Comment by dakaraphi** [comment]
@Huachao This does not work for me.  Previously I was able to fold on comments sections, now I can't fold at all.

Here is an example of a section of the file:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/10656375/32964395-1eb01390-cba1-11e7-822a-758febf0d61b.png">

**Comment by Huachao** [comment]
@dakaraphi add request method(like _GET_, _POST_) at the beginning of each request line should be OK, like:
```http
GET {{host}
```

**Comment by dakaraphi** [comment]
@Huachao This does allow folding, but it is not as useful as before.
I can't see the comments as they get folded.
@Huachao 
The URL's are somewhat cryptic and I can't easily locate them when using this new folding.

Can we have an option to use the original default folding? or can you make it work by folding on the comment line?

**Comment by Huachao** [comment]
@dakaraphi, thanks for your advice. It seems difficult to support both, and current folding logic is from request line to request delimiter(_line starts with `###`_).

So for your case, it seems that comments better be place in a standalone comment line, like my previous code snippet. And the folding result looks like below, does it satisfy your case.

![image](https://user-images.githubusercontent.com/2796177/33639533-aa3032f0-da66-11e7-9eac-cdbbfb2d1776.png)

**Comment by dakaraphi** [comment]
@Huachao thanks for the suggestion, but for my use it is still a regression compared to the original behavior.

When you have hundreds of services, this gets very noisy.  Still better to be like:
```
### First Request
### Second Request
### Third Request
```

Can you use`###` as both the start and stop delimiters?

**Comment by Huachao** [comment]
@dakaraphi I found a way to solve your problem, that is use the line only with delimiters to be end of folding boundary. Since you have comments in delimiter line, it won't be folded. And you can still use your previous indent way to fold like following:
```http
### First Request

    GET https://api.example.com/docs/1

### Second Request

    POST https://api.example.com/docs
    Content-Type: application/json

    {
        "name": "test"
    }

### Third Request

    DELETE https://api.example.com/docs/2

```
![image](https://user-images.githubusercontent.com/2796177/33640126-a82e5894-da69-11e7-9485-f530de371125.png)

Is it OK?

**Comment by dakaraphi** [comment]
@Huachao I think that gets me back to where I was previously.  So that is ok.

Although, delimiter type of folding with comments would be better.  The only reason it would be better is because I can't use level folding when the request uses headers.  The headers can not be indented or they are not recognized as headers.  I don't know if it would be difficult to still recognize the headers when they are indented?

Anyway, if I can get back the original behavior I will be happy enough for now.  Anything else would be just a bonus.  :-)

**Comment by Huachao** [comment]
@dakaraphi I have updated the code to recognize indented headers, will be published in next release

**Comment by Huachao** [comment]
@dakaraphi you can try the latest version 0.16.2

**Comment by dakaraphi** [comment]
@Huachao seems to be working. Thanks!

**Comment by brunolamegolino** [comment]
I use collapse too, can I use it like this?
![image](https://github.com/user-attachments/assets/22ba3a60-7798-4802-8e08-92f172ae47e9)
![image](https://github.com/user-attachments/assets/1e49d43d-dd63-4135-a036-132356d3d6d1)

But the second request doesn't have a send button
