### ISSUE TITLE
About Request Body for POST method~

### ISSUE THREAD

**Issue by wenslim** [Huachao/vscode-restclient#149]
- VSCode Version: 1.19.1
- REST Client Version: 0.16.2

Um, My computer system is windows 10, GET method is good, I refer to your example about POST,but
 I can not accept param in POST method. 
> 1.http
```
POST http://wap.dev/Home/Sign/getCode HTTP/1.1
content-type: application/json

{
    "name": "wenslim"
}
```
> controller
```
public function getCode()
{
        $arr = [
	        'name' => $_POST['name']
        ];
        echo json_encode($arr);
}
```
Somehow I do it in Postman is work well~

**Comment by Huachao** [comment]
@wenslim it seems that since you are using $_POST in your `php` controller, which in fact needs the content type to be `application/x-www-form-urlencoded` or `multipart/form-data` as described [here](http://php.net/manual/en/reserved.variables.post.php). So I think it should work if your update the request body to a x-www-form-urlencoded format as following:
```http
POST http://wap.dev/Home/Sign/getCode HTTP/1.1
content-type: application/x-www-form-urlencoded

name=wenslim
```

**Comment by wenslim** [comment]
@Huachao 3Q ~ 😸
