### ISSUE TITLE
"send request" option in http links selected filetypes

### ISSUE THREAD

**Issue by kenkit** [Huachao/vscode-restclient#204]
- VSCode Version: Latest
- OS Version: Windows 10
- REST Client Version: Latest

Add sendrequest option to specific user defined filetypes

**Comment by Huachao** [comment]
@kenkit what's the user scenario for having this functionality? Do you just want to send an HTTP request inside a normal file, or you already have a file with the same schema as our `.http` schema, but not the same file extension? For the former, you can use the mouse to select the expected text and then use keyboard shortcuts(_Ctrl+Alt+R_) or pressing `F1` to type `Send Request`. For the latter case, just change language mode to `HTTP`, or you can bind this mapping with `files.associations` setting in vscode.

However, for the former case, if you want to enable automatically identify all the HTTP links is not in my plan. Since to recognize some text is a request is based on the request block syntax(`###`) in a file, not simply the URL or the request line. So we don't support this functionality, but you could still send the request as what I said previously.

**Comment by kenkit** [comment]
Exactly, I want to send an HTTP request inside a normal file.
I think you should add a setting where you choose the files which should be scanned for http links

**Comment by Huachao** [comment]
@kenkit my parsing logic won't work for normal requests except your file schema follows `.http` file. And you can try it by setting language mode to `HTTP`.

**Comment by kenkit** [comment]
I see. That can also do.
