### ISSUE TITLE
Show Response Preview in Right Editor 

### ISSUE THREAD

**Issue by chewlm86** [Huachao/vscode-restclient#216]
Hi,

Currently i am working with 3 editor at the same time(Left, Center, Right). 
Would it be possible, to show the response preview in the Right Editor while having the .http in the Center Editor?
Perhaps a configuration to choose where to show the response preview.

**Comment by Huachao** [comment]
@chewlm86 nice suggestion, I have implemented it and will publish it in next release.

**Comment by Huachao** [comment]
@chewlm86 you can use the new setting `rest-client.previewColumn` to control this behavior, and available values are

- left
- center
- right
- current

**Comment by chewlm86** [comment]
Thanks for the up date, it works great with setup where the editor is configured as follow
("rest-client.previewColumn": "right").
| 1 | 2 | **3** |

With the latest update from vs code which allowed splitting the editor vertically as well now. Still works when i set it up like this as well as long it is placed within the range of the first 3 editor.
("rest-client.previewColumn": "center").
| 1 | 3 | 4 |
| **2** | 3 | 4 |

*Preview column is **Bolded**.

**Comment by Huachao** [comment]
@chewlm86 thanks for your information, here I have something to discuss with you, sorry for the late reply. I am thinking about the feature update from VSCode. Do we really need to follow the grid layout of VSCode, that means do we need to expose to our end user for all the column numbers to specify, like `One`, `Two`, `Three`, `Four` and even to `Nine`(Which is defined in VSCode API, and in fact the number can be larger as you wish like `Ten` column). I think it's a bit complex to our users to point out which column they need and even quick know how to count column number. So how about we just expose two options to the `rest-client.previewColumn` instead of current offerings, **`current`** and **`beside`** only which applies for the case of current active column and the column next to current view column(the direction of next column depends on your VSCode setting). This seems more clearer for me, and the only concern is that it doesn't fix well for your case, in three columns layout, you need to put your `.http` in the middle column, and set the setting to `beside`.

Waiting for your great feedback, thanks in advance. 😄

**Comment by chewlm86** [comment]
@Huachao yes i agree that the latest vs code update made positioning the preview column complex with the current implementation.

The new **current** & **beside** implementation you describe make sense.
I think it will work well with my current work flow.

Like you said, if i want it display at 3 i would just place the .http in column _2_ and the preview will appear in **3**.
| 1 | _2_ | **3** |

So i have a split in the last column, i would just place the .http in column _3_ and the preview will be displayed in **4**.
| 1 | 2 | _3_ |
| 1 | 2 | **4** |

But i like to suggest that perhaps having **previous**, **current** & **next** would to give a bit more flexibility on where to position the column. 

*.http column is _Italic_.
*Preview column is **Bolded**.

**Comment by chewlm86** [comment]
@Huachao So that why didn't know that. 
Then that is fine. just keeping it simple. :-)

**Comment by Huachao** [comment]
@chewlm86 I have updated to code to reflect the latest VSCode update, and new setting value would be `current` and `beside`. I still think `beside` seems more appropriate than `next`.

**Comment by Huachao** [comment]
@chewlm86 @svenax I have published a new version 0.19.1, and the setting values of `rest-client.previewColumn` are `beside` and `current` to control the previewing column which reflects the latest VSCode grid layout update.

**Comment by chewlm86** [comment]
@Huachao Thanks, works great. :-}

**Comment by sontd-0882** [comment]
@Huachao How about splitting to `bottom`  or `top` of the current tab.

**Comment by Huachao** [comment]
@sontd-0882 `top` is not supported natively by VS Code, you can open the response tab in the bottom by set `"workbench.editor.openSideBySideDirection": "right"` and `"rest-client.previewColumn": "beside",`

**Comment by terdong** [comment]
> @Huachao How about splitting to `bottom` or `top` of the current tab.

It shoud be "workbench.editor.openSideBySideDirection": "down"
In my case, It worked fine, but resulted in a different layout than I had an expectation. So I rolled back again.
