### ISSUE TITLE
Parameter is not encoded correctly

### ISSUE THREAD

**Issue by jboelter** [Huachao/vscode-restclient#222]
VSCode Version: 1.24.1
OS Version: Microsoft Windows [Version 10.0.17134.112]
REST Client Version: 0.19.0

Steps to Reproduce:

````
# bogus values
@TENANT=8a2ba0b2-e9c5-4a18-8b12-daeb5a4ffaf3
@CLIENT=d6729e93-3471-4580-9571-cc0aded96fe9
@SECRET=f+MjAyM2ItYTc5Mjk2LTgxZmQ+tNjNiZjgwZjBlNGUx=

# get token 
POST https://login.microsoftonline.com/{{TENANT}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{CLIENT}}
&client_secret={{SECRET}}
&resource=https://manage.devcenter.microsoft.com
````

Output from "Rest Client: Copy Request As cURL". Note the secret is not encoded correctly (missing trailing '=') and the first '+' is transcoded as a space. 
````
curl --request POST \
  --url https://login.microsoftonline.com/8a2ba0b2-e9c5-4a18-8b12-daeb5a4ffaf3/oauth2/token \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'grant_type=client_credentials&client_id=d6729e93-3471-4580-9571-cc0aded96fe9&client_secret=f%20MjAyM2ItYTc5Mjk2LTgxZmQ%2BtNjNiZjgwZjBlNGUx&resource=https%3A%2F%2Fmanage.devcenter.microsoft.com'
````
Expected

````
curl --request POST \
  --url https://login.microsoftonline.com/8a2ba0b2-e9c5-4a18-8b12-daeb5a4ffaf3/oauth2/token \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'grant_type=client_credentials&client_id=d6729e93-3471-4580-9571-cc0aded96fe9&client_secret=f%2BMjAyM2ItYTc5Mjk2LTgxZmQ%2BtNjNiZjgwZjBlNGUx%3D&resource=https%3A%2F%2Fmanage.devcenter.microsoft.com'
````

**Comment by Huachao** [comment]
@jboelter thanks for opening this issue, and it's really a bug for your case, however, I still want to discuss with you about this. In your case, the `+` sign is not correctly encoded, the reason for this is that, for `x-www-formurlencode` mime type, `+` sign can be thought of as an already encoded character(space would be encoded as `+`), so it's hard for me how to identify whether the provided string an encoded one or not automatically for this special case. So can we a setting to indicate user's actual purpose, or do you have any better idea? Thanks in advance.

**Comment by jboelter** [comment]
I had expected that the params would be read 'as-is' (assumed un-encoded) and then encoded if appropriate (in a url, in a form body). Something like has the output I expected. This retains the parameter value w/ pre/post whitespace trimmed and w/ leading/trailing newline left intact.  I read through the variable processing code and nothing stood out to me. It might be possible to shorten the escape substitution with a simple global regex replacement.

If I understand correctly, it appears the [HARPostData constructor ](https://github.com/Huachao/vscode-restclient/blob/2afbac4b8e90ac4f7bac54609534aa02bdb3694e/src/models/harHttpRequest.ts#L23) is where this particular example is broken.

This is only replacing the first instance of a '+' to a space.

https://github.com/Huachao/vscode-restclient/blob/2afbac4b8e90ac4f7bac54609534aa02bdb3694e/src/models/harHttpRequest.ts#L28

This split is dropping everything after the second '=' on the now-decoded pair data. I suspect an '&' in the variable would also cause odd behavior on the '&' split.

https://github.com/Huachao/vscode-restclient/blob/2afbac4b8e90ac4f7bac54609534aa02bdb3694e/src/models/harHttpRequest.ts#L33

**Comment by Huachao** [comment]
@jboelter thanks for inspecting the code, and the root cause here is that my extension allows users to provide both encoded and un-encoded params as they wish. So currently I use the [encodeurl](https://www.npmjs.com/package/encodeurl) module to achieve this, it can do some smart job like will not encode the "%" character unless it is not part of a valid sequence (%20 will be left as-is, but %foo will be encoded as %25foo). However, here we met the issue like `+` sign, it can be thought both as encoded space and non-encoded `+` sign. So if I still want to keep the automatically encoding logic, we must ditinguish this case you met. My suggestion is to add a setting named `paramEncoding`, and the corresponding value could be `always`, `never` and `automatic`, the default value is `automatic`. For the default setting value, it will keep current logic that still use the *encodeurl* module to handle the encoding task, which will check whether encoding is needed. And for the `always` setting value, it fits for you, and that means user provide the raw value, and my extension will encode the param value alwasy. Lastly, for the `never` case, my extension will read the provided value as is, no encoding will be performed on this string value.

What's your opinion, thanks in advance.

**Comment by Huachao** [comment]
@jboelter does this change really fix your issue, in my test the `client_secret` is encoded as `f%20MjAyM2ItYTc5Mjk2LTgxZmQ%20tNjNiZjgwZjBlNGUx` different from the expected one `f%2BMjAyM2ItYTc5Mjk2LTgxZmQ%2BtNjNiZjgwZjBlNGUx%3D`

**Comment by jboelter** [comment]
@Huachao I should have updated the complete example, I also found a bug in my proposed fix w/ split. Below works for Send Request and Snippets/Curl.

The extension works as-is per the example below for the 'Send Request' if I encode it to work around the '+' substitution. The transformation into the HARPostData breaks the Curl and Snippet generators however. A (corrected) proposed fix below.

As an aside, pair.split('=', 2) ignores (and drops) anything after the 2nd '='.

````
# bogus values
@TENANT=8a2ba0b2-e9c5-4a18-8b12-daeb5a4ffaf3
@CLIENT=d6729e93-3471-4580-9571-cc0aded96fe9
@SECRET=f%2BMjAyM2ItYTc5Mjk2LTgxZmQ%2BtNjNiZjgwZjBlNGUx=

### get token 
POST https://login.microsoftonline.com/{{TENANT}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{CLIENT}}
&client_secret={{SECRET}}
&resource=https://manage.devcenter.microsoft.com
````

**Send Request**
````
POST https://login.microsoftonline.com/8a2ba0b2-e9c5-4a18-8b12-daeb5a4ffaf3/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: vscode-restclient
Accept-Encoding: gzip, deflate
Content-Length: 187

grant_type=client_credentials&client_id=d6729e93-3471-4580-9571-cc0aded96fe9&client_secret=f%2BMjAyM2ItYTc5Mjk2LTgxZmQ%2BtNjNiZjgwZjBlNGUx=&resource=https://manage.devcenter.microsoft.com
````

**Copy Request As cURL** other snippets also appear correct
````
curl --request POST \
  --url https://login.microsoftonline.com/8a2ba0b2-e9c5-4a18-8b12-daeb5a4ffaf3/oauth2/token \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'grant_type=client_credentials&client_id=d6729e93-3471-4580-9571-cc0aded96fe9&client_secret=f%2BMjAyM2ItYTc5Mjk2LTgxZmQ%2BtNjNiZjgwZjBlNGUx%3D&resource=https%3A%2F%2Fmanage.devcenter.microsoft.com'
````

````diff
diff --git a/src/models/harHttpRequest.ts b/src/models/harHttpRequest.ts
index 2129bd4..621c1ff 100644
--- a/src/models/harHttpRequest.ts
+++ b/src/models/harHttpRequest.ts
@@ -25,12 +25,12 @@ export class HARPostData {
     public constructor(public mimeType: string, public text: string) {
         if (mimeType === 'application/x-www-form-urlencoded') {
             if (text) {
-                text = decodeURIComponent(text.replace('+', '%20'));
+                text = decodeURIComponent(text.replace(/\+/g, '%20'));
                 this.params = [];
                 let pairs = text.split('&');
                 pairs.forEach(pair => {
-                    let key: string, value: string;
-                    [key, value] = pair.split('=');
+                    let [, key, value] = /([^=]+)=?(.*)/.exec(pair);
+                    console.log(key, value);
                     this.params.push(new HARParam(key, value));
                 });
             }
````

**Comment by Huachao** [comment]
Does this fix really pass your original request in the issue, in the original secret variable, the value of it is a un-encoded string, which is different from your current encoded one in latest comment, do you really just want to pass the case of encoded one, if so, that's ok

**Comment by jboelter** [comment]
The Send Request code path works by pre-encoding the '+' as %2B to avoid the %20 substitution. The patch fixes the snippet generation and 'cURL' generation with an embedded '=' in the value so it splits the key/value correctly.

I do think it would be useful to introduce overall or per-variable encoding/decoding options.  e.g. URL, base64.

**Comment by Huachao** [comment]
@jboelter I have added the setting `formParamEncodingStrategy` to control the form data encoding behavior.  Provided enum values for this setting are `automatic`(default), `never` and `always`. The default `automatic` strategy will check the provided form parameter encoded or not and does the encoding job automatically. However, it doesn't work for the parameter value `+`, it will treat it as an encoded space character. So in order to work for your case, treat all the user provided form data as raw value, and do the encoding job anyway, you need to set the `formParamEncodingStrategy` setting to **`always`**. And my extension will do the encoding job for you.

**Comment by Huachao** [comment]
@jboelter you can try the latest version 0.19.1 to verify the fix with the new setting `rest-client. formParamEncodingStrategy`. And you no longer need to partial encode the characters, just set it to `always`, that should be the case for you.
