### ISSUE TITLE
Wrapping of long strings in output window

### ISSUE THREAD

**Issue by shytikov** [Huachao/vscode-restclient#24]
It would be nice to have results in response window be wrapped by default. In case if you're having long result string (token, for example) it's very inconvenient to work with such data.

**Comment by shytikov** [comment]
I know that issue is supposed to be fixed, but result is still not that satisfying, at least for applications I'm using REST client...

I'm still experiencing very long poorly wrapped responses (it's Windows based servers fault, of cause), but it would be nice to fix that on client side somehow.

For example, add setting for strict wrapping margin. Wrap response on 80 chars, for example. It should solve problem for ever.

Because right now in complex cases (long hashes) I'm getting output window that has no horizontal scroll, very hard to copy it's content and only way around is to save whole response (which is overkill in most of the cases).

I would appreciate if this one could be reopened.

**Comment by Huachao** [comment]
@shytikov thanks for your feedback, I will fix it ASAP

**Comment by shytikov** [comment]
Thank you so much, @Huachao!

**Comment by Huachao** [comment]
@shytikov BTW, I want to mention that we have ways to copy response content with just one click, in the preview panel, you could find the save response button in the upper right corner, it will help you to save response in any case.

**Comment by Huachao** [comment]
@shytikov after I think about your suggestion, my original fix is using the css style `white-space: pre-wrap;` which means the rendering is adapt to the panel size and monitor size. However, if I changed as you suggested, setting a max length in css like `max-width`, will make the rendering not fitting the monitor in some large screens which they could display more characters than max length. Since I am not quite familiar with CSS, do you have any suggestions?

**Comment by Huachao** [comment]
@shytikov I add a `word-break` CSS style which will break long words

**Comment by Huachao** [comment]
@shytikov you could try the latest version to verify, thanks

**Comment by shytikov** [comment]
Yes, right now it looks more usable! Thanks!
