### ISSUE TITLE
Recursive Variables

### ISSUE THREAD

**Issue by kferrone** [Huachao/vscode-restclient#247]
Would be nice to have recursive variables so one variable can be made up of more than one variable. 

Example: 

```
@host = 'localhost'
@port = '8080'
@url = http://{{host}}:{{port}}

GET {{url}}/msg HTTP/1.1
```

Unfortunately I get an error like below instead:

```
Invalid URI "http:///%7B%7Bh%7D%7D:%7B%7Bp%7D%7D/msg"
```

Keep up the awesomeness!
Thanks for hearing me out.

**Comment by kferrone** [comment]
Good to hear you are working on it. I'll keep an eye out. Cheers!

**Comment by pvoisin** [comment]
Hello! Any update on this? It'd be really, really useful (not to say "necessary"... :))
Need any help on that?

**Comment by Huachao** [comment]
@pvoisin For file variable references other file variables are still working in progress

**Comment by Huachao** [comment]
@kferrone @pvoisin @thehig @RafaelAdao @jianwu @druppelt I have implemented the feature that file variables can reference other variables as you described in the issue, and it will be published in next release. @kferrone one thing to notice in the example you illustrated before, you need to remove the single quote in the variable value, since the variable replacement logic will leave the value as is. Finally, thanks for your great suggestion.

**Comment by kferrone** [comment]
Wicked good! I'll be enjoying this new feature.
