### ISSUE TITLE
Use yaml

### ISSUE THREAD

**Issue by jgroom33** [Huachao/vscode-restclient#287]
This project [strest](https://github.com/eykrehbein/strest/blob/master/README.md) is looking for a UI implementation.

It would be great if vscode-restclient allowed execution of individual requests from a .strest.yml file.

**Comment by Huachao** [comment]
@jgroom33 @eykrehbein nice suggestion. This feature request can be divided into 2 tasks. I think we need to solve these two issues to achieve the goal. First, my extension is able to recognize requests defined the yaml or some request schema in a file. Second, my extension is able to run all the requests sequentially or parallelly defined in a file(See issue #21).

**Comment by jgroom33** [comment]
I'd like to leverage the strengths of each of these projects individually.
Use strest for multi file and multi request execution (good for CI)
Use vscode-restclient to perform manual executions (good for development).

This format is slightly verbose, but it should handle all requirements:
http://www.softwareishard.com/blog/har-12-spec/#request

**Comment by Huachao** [comment]
@jgroom33 Personally I think my extension uses the raw HTTP format to organize requests in `http` file, if I want to support the test functionality(#267), it seems I just need to implement the `validation` section of your `YAML` file. So I originally don't intend to support other formats like `HAR` in a higher priority. Since I already supported the request name feature for each request like following by adding a metadata in a comment line:
```http
# @name login
POST https://api.example.co/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar
```
So if I need to support the validation logic, I think we can leverage from current logic, like creating new metadata besides `name` to achieve these goals.

**Comment by jgroom33** [comment]
ok.  thanks for the consideration
