### ISSUE TITLE
Unexpected token U

### ISSUE THREAD

**Issue by ritcoder** [Huachao/vscode-restclient#31]
- VSCode Version: 1.4.0
- OS Version: Windows 10
- REST Client Version: 0.7.2

Steps to Reproduce:

1. Enter `GET http://wwww.bing.com HTTP/1.1`
2. `Ctrl`-`Alt`-`R`

I get the error above. I was working find just a few minutes ago so not sure what could be the case.

R.

**Comment by Huachao** [comment]
@ritcoder this error seems normally happened at JSON.parse, which getting a parameter is undefined.

- I want to confirm can you repro this error for other urls
- you mean you can work earlier, and failed since some time, so I'd like you to check files(history.json and cookie.json) exist under this path `%USERPROFILE%\.rest-client` and whether they are real json
- Can you toggle develop tools in vscode(Help -> Toggle Developer Tools) when running the command

Thanks for your reporting. And I can't repo in my machine by now

**Comment by ritcoder** [comment]
I checked `cookie.json` and indeed, it did not contain correct json.

The ending of the file was


"www.bing.com":{"/":{"SRCHUID":{"key":"SRCHUID","value":"V=2&GUID=85BD4FE597F142D3A3D390D8330436C6","expires":"2018-08-19T11:39:50.000Z","domain":"www.bing.com","path":"/","hostOnly":true,"creation":"2016-08-19T11:39:50.778Z","lastAccessed":"2016-08-19T11:39:50.778Z" } } } }UIDB":{"key":"MUIDB","value":"1B8CFC8E99BA69BD33C2F5F898DC68BA", "expires":"2018-08-19T11:39:50.000Z","domain":"www.bing.com","path":"/","httpOnly":true, "hostOnly":true,"creation":"2016-08-19T11:39:50.780Z","lastAccessed":"2016-08-19T11:39:50.780Z"}}}}


Everything got back to normal after deleting the invalid part of the json.

`UIDB":...`

It is working now. Do you have any idea of what could have caused the invalid json to be written to the file?

**Comment by Huachao** [comment]
@ritcoder I think it may be the concurrency bug of the cookie store I used, see [here](https://github.com/mitsuru/tough-cookie-filestore/issues/3). I will try to use other ones.

**Comment by ritcoder** [comment]
Cool. Now that I think about it, I was using it from two tabs. Anyway, will see if I can reproduce it and check with the next update. Thanks.

**Comment by Huachao** [comment]
@ritcoder I have published the new version 0.7.3 which fixes the bug, you can have a try. :smiley:
