### ISSUE TITLE
How to query the microsoft graph thanks to rest client

### ISSUE THREAD

**Issue by TechWatching** [Huachao/vscode-restclient#339]
I don't really understand how to use the REST client and in particular the Azure Active Directory Token system variable to query the microsoft graph.
The AAD token I can retrieve thanks to REST Client does not seem to have the right on the Microsoft Graph as I receive a 403 with the following request 
```
GET https://graph.microsoft.com/v1.0/me/ HTTP/1.1
Authorization: {{$aadToken tenantId}}
```
Requesting a token for the Microsoft Graph API usually involves registring an application in the AAD and passing a client_id and a client_secret, but I don't see where to pass them here.

**Comment by flanakin** [comment]
I wasn't able to get this to work with Microsoft Graph. I know there were changes to Azure AD auth, which Microsoft Graph requires, but do not know the details and did not have enough time to investigate this. I believe we'll need another community contribution to support Microsoft Graph.

**Comment by mthierba** [comment]
@TechWatching This should be possible once #218 has been resolved (PR #275) - which will allow you authenticate against your own custom AAD application. There has been some movement on #218 recently, so fingers crossed! (I'm also waiting for this.)

**Comment by ckihm** [comment]
@TechWatching I was able to call the Graph API. I created an Service Principal (App Registration) in my AAD Tenant and granted the needed Graph permissions to it with an admin consent. Now I am able to request an AT for my Service Principal and can use the Token to perform calls on the Graph API. 

Depending on the API you want to request, you may be able to use the client credentials flow instead of the resource owner password flow. This would be better as you would not perform an impersonification and you would no longer need to provide the user credentials.

`
\### AT for Graph API to RestUI with Resource Owner Password Flow
\# @name getAccessToken
POST  https://login.microsoftonline.com/{{tenant-id}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&scope={{permission}}
&client_id={{client-id}}
&client_secret={{client-secret}}
&username={{username}}
&password={{password}}


\### Create New TokenLifetime Policy
POST https://graph.microsoft.com/beta/policies/tokenLifetimePolicies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "displayName":"CustomTokenLifetimePolicy",
  "definition":["{\"TokenLifetimePolicy\":{\"Version\":1,\"AccessTokenLifetime\":\"8:00:00\"}}"],
  "type":"TokenLifetimePolicy"
}
`

**Comment by TechWatching** [comment]
Yes indeed this works fine :), but the original issue was more about using `$aadToken` mechanism.

**Comment by darrelmiller** [comment]
I added a PR that creates an $aadV2Token mechanism that can call Microsoft Graph.  https://github.com/Huachao/vscode-restclient/pull/649  Feedback welcome!

**Comment by TechWatching** [comment]
I am willing to try it. But how can I test it. If I clone your branch from the PR, what do I have to do to test it in my vs code ? Sorry, never try to use rest client from the source code.

**Comment by darrelmiller** [comment]
@TechWatching That's the most awesome part.  Clone it, load it into VS Code and then select Run and it will spin up a new instance of VS Code with the extension installed.  You can even debug and step through the extension.

**Comment by TechWatching** [comment]
Hum, I must have missed something because I correctly retrieved a token but the query to graph failed anyway : 
```json
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "date": "2020-08-05T16:01:19",
      "request-id": "afb38a7e-6cc0-4a92-80a0-857e9dbd04d1"
    }
  }
}
```
I try with this one (same response without the tenant Id specified).
```http
GET https://graph.microsoft.com/v1.0/me
Authorization: {{$aadV2Token tenantId:xxx-xxxx-xxx-xxx}}
```

Another thing to note is that pop up to login in the browser shows up too late i.e. after the pop up where I can click on "Done". It still work because I can click on "Try again" and it will show up (twice) but it's weird. I will update my vs code in case my version is too old.

**Comment by darrelmiller** [comment]
@TechWatching Depending on what request you are making you will need to consent the RESTClient extension access to your data.  You do this by providing the scopes attribute.  Each reference documentation page on Microsoft Graph tells you which scope the application needs to consent to before it can make the call.  e.g. https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#permissions

Interestingly, User.Read is granted by default so you shouldn't need to add a scope to be able to call the `https://graph.microsoft.com/v1.0/me`.

I haven't seen the issue you describe around the browser only showing up after clicking Try Again.  The popup code was copied largely from the existing aadToken variable.  What browser are you using?

**Comment by Huachao** [comment]
@TechWatching you can try the latest version 0.24.2, thanks for the contribution from @darrelmiller
