### ISSUE TITLE
Parse error on nonstandard HTTP codes

### ISSUE THREAD

**Issue by ringosham** [Huachao/vscode-restclient#359]
- VSCode Version: 1.32.3, 1.33.1
- OS Version: Manjaro, Windows 10
- REST Client Version: 0.21.2

Steps to Reproduce:

1. Host a restlet server. Have an API call that returns restlet errors.
2. Make a request to connect to it.
3. Wait for a nonstandard response like 1000.

Below is the same request made in postman (on Windows).
![Annotation 2019-04-19 174124](https://user-images.githubusercontent.com/7325740/56433891-6cd00a00-62ca-11e9-972b-5a2d0d97143a.png)

**Comment by ringosham** [comment]
Here are the headers.
![Annotation 2019-04-19 174658](https://user-images.githubusercontent.com/7325740/56434125-3e066380-62cb-11e9-986e-6f9311d4cb31.png)

**Comment by Huachao** [comment]
@ringosham why do you want such a nonstandard status code, and most web frameworks only support status code less than 1000. BTW, can you provide a public url for me to verify?

**Comment by Huachao** [comment]
@ringosham why do you want such a nonstandard status code, and most web frameworks only support status code less than 1000. BTW, can you provide a public url for me to verify?

**Comment by ringosham** [comment]
While a 4 digit status code is so uncommon (You are not supposed to use this status code in APIs anyway. It's reserved in the framework's code, which is Restlet), I think it's better for the plugin to show something instead of just a parse error.

As for a public URL... I don't have a domain to host one. This server is locally deployed, sorry.
The best I can help is providing you with a link to their source.
https://github.com/restlet/restlet-framework-java/blob/2.3/modules/org.restlet/src/org/restlet/data/Status.java

**Comment by ringosham** [comment]
The response itself doesn't seem to be any different than any other standard response other than it's 4 digits.

**Comment by ringosham** [comment]
I've made a small test server that throws an 1001 status code.
Simply made a post call to localhost:8080/test/test
https://drive.google.com/open?id=1i7MWFaULsVRVMnqoTev02g1LLOODzvuu

**Comment by Huachao** [comment]
@ringosham thanks for your fantastic `jar` package, and I have tested the url, the error is `Parse Error`, and this error will also occur some tools like `Postman`, the root cause is that the rest client extension is built on the Node.js, and the underlying http parser that Node.js uses will do the status code check https://github.com/nodejs/http-parser/blob/5c17dad400e45c5a442a63f250fff2638d144682/http_parser.c#L880-L882 it will ensure the status code is not larger than 999. And I don't find any indication that Node.js community will solve this issue. Sorry for the inconvenience.
