### ISSUE TITLE
Can not search/find (Ctrl+F) inside Response tab

### ISSUE THREAD

**Issue by internetz** [Huachao/vscode-restclient#42]
- VSCode Version: 1.5.3
- OS Version: Ubuntu 16.04 (KDE Neon)
- REST Client Version: 0.8.4

Steps to Reproduce:
1. Request any Resource. e.g. http://github.com
2. The Response is shown but you can not search/find (Ctrl+F)  inside the response tab

**Comment by Huachao** [comment]
@internetz This is related to VS Code limitations, Microsoft/vscode#8794 and Microsoft/vscode#12215. And I will follow up the issue in vscode, and will try to implement it in VS Code when I have time. Thanks

**Comment by shahidmau** [comment]
It is required option. You can see "**ES Query**" plugin, they are providing search option in result window.

**Comment by Huachao** [comment]
@shahidmau since I am using html to preview the result, while they use text document to display the result. And `vscode` has limitation in searching result in preview page. And in #72 , I am considering to add a new command to display the response in text document, so that you can search. And currently, you have to save the response, and search what you need

**Comment by shahidmau** [comment]
ok, so what you can do is to provide an option to show output in either plain format or html format.
You can give toggle/switch button some where in output response.
Plain text must support search option. **ES Query** is also showing plain text but it looks good.
It is required because sometime we have output response of thousands of lines and we can not scroll manually to find our desired text and html format becomes very slow.

**Comment by Huachao** [comment]
@internetz @shahidmau I have added a new way to display result in an untitled document, and it seems can solve your problem, and I will publish this version ASAP

**Comment by Huachao** [comment]
@internetz @shahidmau since version 0.13.0, you can preview the response in the editor directly(previously only allow in webview, which vscode has some limitation), you can experience this feature by set the setting `rest-client.previewResponseInUntitledDocument` to `true`.

So I'd like to close the issue now, and supporting find in the webview is still depending on vscode.

**Comment by Huachao** [comment]
@internetz @shahidmau in latest vscode 1.15.0, you can already search in preview page with keyboard shortcut `Cmd+F`. With this feature, you can set rest-client.previewResponseInUntitledDocument to false again.

**Comment by ggayan** [comment]
@Huachao It looks like searching in the preview webview is not working anymore. I am willing to check how can this be patched, but I am not sure where to look. Do you have any pointers?

**Comment by Huachao** [comment]
@ggayan do you mean you can't get the highlighted results after you provide the searching words , can you please provide a screenshot
