### ISSUE TITLE
Unable to send request, getting read ECONNRESET

### ISSUE THREAD

**Issue by rithinskaria** [Huachao/vscode-restclient#531]
Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Rest Client : 0.23.1
Steps to Reproduce:

1. Calling an API gives read ECONNRESET

![image](https://user-images.githubusercontent.com/38252976/75364782-46afc900-58e2-11ea-8133-fc06137bca30.png)

**Comment by Huachao** [comment]
@rithinskaria does retry work, or this error happens on other requests? Does rolllback to versions like 0.22.2 work?

**Comment by Cyberodd** [comment]
> @rithinskaria does retry work, or this error happens on other requests? Does rolllback to versions like 0.22.2 work?

Rolled back to 0.22.2 and got the same error.

**Comment by Cyberodd** [comment]
bumping this because I still have this issue

**Comment by dadmakestech** [comment]
Was working with the plugin for about 2 hours, and now seeing this issue too.

**Comment by erichbehrens** [comment]
I had the same issue and it seems to work fine when I add the `Connection: keep-alive` header to the request.

**Comment by happyraver1958** [comment]
This will definitely sound like a bad question because I am a newbie, but where exactly would I write "Connection: keep-alive"? Does it go in the declaration, in the .rest file or elsewhere?
I am experiencing this problem by following a video tutorial on YouTube, it works as expected in the video, but I get "read ECONNRESET" when I use the "Send Request" link from my .rest file.
<img width="723" alt="ECONNRESET error" src="https://github.com/Huachao/vscode-restclient/assets/7854082/faae338e-09e0-4685-9b01-192934f23ec1">

**Comment by Nainah23** [comment]
F
