### ISSUE TITLE
Authorization token header not capitalized

### ISSUE THREAD

**Issue by eric-pfi** [Huachao/vscode-restclient#553]
- REST Client Version: 0.23.2
- VSCode Version: 1.43.2
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Make a request with "Authorization: Bearer Test"
2. Log the http headers received by the server. The application receives "authorization: Bearer Test". Note that the actual delivered header identifier starts with a lowercase 'a' rather than uppercase.

I recently took over responsibility for a legacy code base that has custom-built bearer token authentication. It looks at HTTP headers for "Authorization", not "authorization". The MDN spec has the request header showing as capitalized, so it seems expecting it to be capitalized isn't unusual.

I'm working around the issue in my local copy of the server for now, and I'd prefer not to check in a change that simply enables a tool. If you add build instructions, I'm happy to try and put together a pull request.

**Comment by eric-pfi** [comment]
I did some more searching, and found [this issue](https://github.com/zalando/connexion/issues/855) on another project. The explanation / comments there are useful. In particular, the citation of section 8.1.2 of the spec that says that header labels should be compared in a case-insensitive manner. My application currently does not support HTTP/2, but hopefully this is enough justification that I can convince other developers to look for the header in a case-insensitive manner.

Having said that, I have a suggestion. Since you can specify HTTP protocol version in the URL per the examples, I would suggest that:

- If HTTP/1.x is specified, use mixed case header values as defined [here](https://www.iana.org/assignments/message-headers/message-headers.xhtml), or
- Use the label specified in the send request as is rather than changing it

Another possible idea
- disallow the use of mixed-case keywords in the request unless HTTP/1.x is specified as a protocol
- Require lower-case keywords if HTTP/2 is supported or a protocol is not specified. The thing that really confused me was the assumption that the header tag I specified would be the one sent to the server.

These changes are more complex, and beyond what I am willing to attempt in a pull request, unfortunately.

**Comment by Huachao** [comment]
@eric-pfi HTTP request/response headers names case-insensitive doesn't only apply on the HTTP/2 case, but also applies to the HTTP/1.0 and HTTP/1.1 according to the original spec https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html. Back to our case, since VSCode extensions all build on the Node.js framework which will convert all the characters to lowercase The discussion is already locked since the early days of Node.js. https://github.com/nodejs/node-v0.x-archive/issues/1954. So there seems no way for server to receive the non-lowercase headers if the request is sent from the Node.js.
