### ISSUE TITLE
POST with Basic authentication does not work

### ISSUE THREAD

**Issue by ilog2000** [Huachao/vscode-restclient#569]
- REST Client Version: 0.23.2
- VSCode Version: 1.44.2
- OS Version: Windows 10 1909

Steps to Reproduce:

```
@baseURL = https://someurl.com
@username = test
@password = psw
@agent = sample

POST {{baseURL}}/api/endpoint  HTTP/1.1
User-Agent: {{agent}}
Accept: application/json
Content-Type: application/x-www-form-urlencoded;charset=utf-8
Authorization: Basic {{username}} {{password}}

type=sample&param=test
###
```
Authorization header is missing in request. The same if I use colon. Only directly generated outside base64 string works

**Comment by ilog2000** [comment]
UPDATE: Sorry, not completely correct bug report. Request works, the issue is that Authorization header is not shown in request-response window when internal base64 encoding applied.

**Comment by Huachao** [comment]
@ilog2000 this is by design currently, since we pass this directly to Node.js and remove the `Authorization` header in your request, and Node.js will be responsible for re-generating it again. However, I can't retrieve it from this info again.  The request-response window will only display the request headers that the extension sends to Node.js.
