### ISSUE TITLE
Support Digest Authentication

### ISSUE THREAD

**Issue by enko** [Huachao/vscode-restclient#61]
- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.10
- REST Client Version: 0.12.0

Steps to Reproduce:

1. Try a request with this code:

```
GET https://user:passwd@httpbin.org/digest-auth/auth/user/passwd
```

[The readme](https://www.npmjs.com/package/request#http-authentication) of the request library specifies that Digest authentication should work if you specify the option `sendImmediately`.

**Comment by Huachao** [comment]
@enko Thanks for your usage and feedback. According to the [code](https://github.com/request/request/blob/master/lib/auth.js#L30), for Basic Auth, the `sendImmediately` should be true, since it needs to append the `Authorization` header in request, while for Digest Auth, the value should be false. However, if user provides user and pass only in the url of request, it seems impossible to know whether the request targets Basic or Digest Auth, since both of them can use this syntax, and it's not sure how to set the `sendImmediately` flag.

So I am considering if I need to provide a way to let user specify the user, pass and the auth type, and do you have any suggestions?

**Comment by ellogwen** [comment]
So, it is not possible to do digest requests without using curl by now?

**Comment by Huachao** [comment]
@ellogwen no, I just mean we need a way to represent Digest Auth for request in my extension

**Comment by ellogwen** [comment]
@Huachao how about the workspace settings for that cases, something like that:
```
"rest-client.environmentVariables": {
	"local": {
		"host": "192.168.10.88",
		"token": "test:abcdefghijklmnopqrstuvwxyz",
		"auth": "digest"
	}
}
```
and then do the request calls to your lib accordingly?

**Comment by Huachao** [comment]
@ellogwen nice suggestion, I will implement this ASAP and after that I will tell you more details

**Comment by Huachao** [comment]
@enko @ellogwen I have supported this and you can use this by setting Authorization header like following: `Authorization: Digest username password`

And both `username` and `password` can also be the environment variables.

@ellogwen The difference between your suggestion and my implementation is that, I use `username` and `password` separately while you merge them in one.

**Comment by ellogwen** [comment]
@Huachao thank you very much. I will test it when the update is ready

**Comment by Huachao** [comment]
@ellogwen @enko  you can try the latest version 0.14.0 to test, you can set the Authorization header in following format:
```http
Authorization: Digest username password
```
You just need to replace user name and password to your own, you can even use custom variable in user name and password
