### ISSUE TITLE
Headers are not shown for an image response

### ISSUE THREAD

**Issue by ArthurHNL** [Huachao/vscode-restclient#612]
- REST Client Version: `v1.46.0`
- VSCode Version: `v0.24.1`
- OS Version: Windows 10 Pro version 1909

When executing a request that returns an image, the response HTTP headers are not shown.

Steps to Reproduce:

1. Create a request to request an image, eg:
```http
GET https://humao.gallerycdn.vsassets.io/extensions/humao/rest-client/0.24.1/1592028624802/Microsoft.VisualStudio.Services.Icons.Default
```

2. Execute the request

**Comment by Huachao** [comment]
@ArthurHNL this is by design that only renders the actual images for the image response in **webview** preview mode. We have two ways to view the actual response headers for the image response:

1. Set the preview mode to text document instead of webview with options `"rest-client.previewResponseInUntitledDocument": false`
2. Use the `HEAD` request instead of `GET` request method to retrieve image response headers only if the server-side supports this.
