### ISSUE TITLE
REST Client extension disabling effects of Bracket Pair Colorizer 2 extention

### ISSUE THREAD

**Issue by Pika-Pool** [Huachao/vscode-restclient#624]
- REST Client Version: v0.24.1
- VSCode Version: 1.46.0
- OS Version: Windows 10

Steps to Reproduce:

1.    install bracket pair colorizer 2 extenson for vscode
2.    install REST Client extension for vscode
3.    enable REST Client extension
4.    reload vscode

REST client is somehow disabling the bracket pair colorizer 2 and possibly setting the colors to default.

When REST Client is disabled:
![rest client disabled](https://user-images.githubusercontent.com/33688622/85395758-4234ad80-b56e-11ea-8ac4-934cc10953c9.png)

When REST Client is enabled
![rest client enabled](https://user-images.githubusercontent.com/33688622/85395761-44970780-b56e-11ea-9dd7-9720bce45bb4.png)

Hint: Look at the font color of brackets

**Comment by Huachao** [comment]
@Pika-Pool I followed your step that first disables my extension, then enables my extension, and it reproduces. However, I checked with VSCode built-in command `Show Running Extensions`, I found the **Bracket Pair Colorizer 2** reported an issue with following output
```json
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 72,
		"activateCallTime": 30,
		"activateResolvedTime": 94,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Cannot invoke loadWASM more than once."
		}
	]
}
```

The root cause seems `Cannot invoke loadWASM more than once.`. I also found there is a similar issue in https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/295 . I think the bracket colorized extension should be responsible for fixing it. 

I also found if we restart the VSCode, the problem resolved.
