### ISSUE TITLE
is this addon still work?

### ISSUE THREAD

**Issue by mhamri** [Huachao/vscode-restclient#687]
I just installed this addon and made a .http file. but unfortunately no "send request" appear on top of the first line in the vscode. I closed and reopened the vscode but nothing happened. so I was thinking something should be broken 

![image](https://user-images.githubusercontent.com/8991783/94251652-6761ff00-ff55-11ea-9523-71d1b53f7ec6.png)

Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by mheyberg** [comment]
same here, 

Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by JtMotoX** [comment]
I would recommend you to check out the documentation ([link](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)).  It is written very well by the author and it should have everything you need.

To answer your question.  I see a couple issues with your .http file.

1. [Circled in red in screenshot below] - You need to separate each request with ###.  This is mentioned under the "Select Request Text" section of the documentation.
1. [Circled in yellow in screenshot below] - The format for header is simply ```header_name: header_value``` (e.g. ```Content-Type: application/json```).  This is mentioned under the "Request Headers" section of the documentation.  Also you should use "application/json" instead of just "json".

![image](https://user-images.githubusercontent.com/7191259/94321784-7d67c380-ff45-11ea-97c4-da0617150cb8.png)

**Comment by Huachao** [comment]
@JtMotoX thanks for your explanation.

**Comment by mhamri** [comment]
@JtMotoX thanks, I were used this addon before and it was working but now it doesn't. and adding ### doesn't do anything 

I tried first with single GET method and no "send request" appeared in the editor. 
I've also tried with the "command bar (Ctrl+shift+p)" to send the request. this is intermitent. sometimes show the sidebar, sometimes doesn't show

![image](https://user-images.githubusercontent.com/8991783/94536756-5a0a8480-0275-11eb-97cb-962fbeb7e9b1.png)

**Comment by mhamri** [comment]
@Huachao  maybe you want to add this to the documentation, having `  "editor.codeLens": false,` in the setting is removing the "send requet" button

**Comment by JtMotoX** [comment]
@mhamri actually the documentation pretty much already mentions this.

> "CodeLens support to add an actionable link to send request"

**Comment by mhamri** [comment]
well, it's not clear enough and doesnt' pass the meaning at all. it should mention it as a requirement or tell what will happen if it's disabled. 

`Codelens support` means the plugin support code lens, doesn't mean it doesn't work if it's disabled. some paraphrase is needed. 

i would rewrite it as:

> CodeLens is required to add an actionable send-request button on top of each http method. if you are having trouble viewing the send-request button, please make sure the setting for `editor.codeLens` is not set or it's equal to `false`

**Comment by Huachao** [comment]
@mhamri it's welcomed to open a PR
