### ISSUE TITLE
Files are opened on the right of the REST client result after REST call

### ISSUE THREAD

**Issue by chamerling** [Huachao/vscode-restclient#723]
- REST Client Version: 0.24.4
- VSCode Version: 1.51.1
- OS Version: OS X 10.13.6

Hello,

Every time I want to open a file after I used REST Client, the file is opened "on the Side" of the REST Client response which is already opened "on the Side" of my files.

Steps to Reproduce:

1. Open a REST Client file
2. Make a REST Client call, the result is opened "on the Side" 
3. Open a file from the VSCode file tree

Expected: 

Have a configuration flag which allow to not open the new file "on the Side" but on the left and keep the REST Client result opened "on the Side"

**Comment by ericnoguchi** [comment]
+1 this feature, its really annoying I have to keep closing the response window after every request. 

Great extension BTW!

**Comment by Huachao** [comment]
@chamerling @ericnoguchi The underlying problem is which side of VS Code editor take focus, by default, the rest client extension setting `"rest-client.previewResponsePanelTakeFocus"` is set to `true`, and in this case, the response tab will take focus, after that each opened file will be opened in the same side of the response.  If you set `"rest-client.previewResponsePanelTakeFocus"` to `false`, the behavior will work as you expect.

Since the underlying problem is editor focus, one simple way is to click the original side editor to take focus manually.

**Comment by chamerling** [comment]
OK, works, thx a lot.
