### ISSUE TITLE
hyperlink address in response includes trailing double quote (version 0.24.5)

### ISSUE THREAD

**Issue by thofil73** [Huachao/vscode-restclient#816]
My JSON response contains download links for files like
{
  ...
  "url": "https://path/to/file.ext"
}

RestClient v0.24.5 creates a hyperlink from it with the following target address:
  https://path/to/file.ext"
When I click the hyperlink, it won't resolve because of the trailing double quote added by RestClient.

In v0.24.4 this worked fine. RestClient created target address as expected:
  https://path/to/file.ext

**Comment by adibradfield** [comment]
I have just had to come off quite an embarrassing with a supplier where I said that the URLs that their API was generating weren't working properly. It was actually this issue 😂

**Comment by adibradfield** [comment]
If it helps in finding what caused this bug, I first reported the "issue" to the supplier on the 8th April, so the bug was released either then or the day before

**Comment by asmith3006** [comment]
I just spent 5 minutes making a screenshot to demonstrate this issue!

I'm getting the same thing:

VSCode 1.55.2
Restclient: 0.24.5

**Comment by asmith3006** [comment]
I've had a look through the code but I'm not knowledgeable enough to resolve this, is there a workaround?

**Comment by adibradfield** [comment]
This has been bugging me so decided to look into it. Looks like the update to the highlight.js dependency is the culprit. There is a PR there which HTML encodes quote characters to `&quot;`  https://github.com/highlightjs/highlight.js/pull/2235. 

This has then broken the regex that is used to detect URLs in the `addUrlLinks` method in `src/views/httpResponseWebview.ts` since there isn't actually a quote mark in the string anymore.

The simplest fix would be to just roll the version back, but it was probably upgraded for a reason.

I don't think it will be possible to fix the regex to not include `&quot;` in the match, without also breaking query parameters

Possibly could get it to work by updating it to use a replacer function instead, which could non URL characters, strip them from the anchor href and text, then add them back in outside the anchor. 

I'll see if i can get a PR together at some point soon

**Comment by adibradfield** [comment]
Just opened PR #852

**Comment by Huachao** [comment]
@asmith3006 @adibradfield @thofil73 @nasypovd @SawatzkiWestfalia @johnnytemp this has been fixed in the lastest verison 0.24.6 and you can have a try, thanks @adibradfield's help

**Comment by thofil73** [comment]
Hello Huachao,

Thank you!
I confirm that the issue is gone with latest version 0.24.6 !
Just tested it successfully.

Best regards,
Thorsten.

**Comment by asmith3006** [comment]
Tested here too, thank you!!!! @Huachao  love your work and thank you @adibradfield for sorting this particular issue.
