### ISSUE TITLE
Open-VSX

### ISSUE THREAD

**Issue by SebTM** [Huachao/vscode-restclient#860]
Hey,

I saw the warning on Open-VSX and thought it might be cool when you have time and like to claim/verify there? :)
https://open-vsx.org/extension/humao/rest-client

Best Regards

P.S. If you give me permission, because you like the idea but don't want make it, I'm happy to help :)

**Comment by Huachao** [comment]
I don't want the extension to be published by Open-VSC

**Comment by filiptronicek** [comment]
Hey there @Huachao 👋, I'm a commiter to Open VSX. I saw that since 2020, this extension has been automatically published by us to https://open-vsx.org [[1](https://github.com/open-vsx/publish-extensions/commit/8a4c2ea785ec0d4c64c0535e16a968a14e4071d1)], which does not need any maintaining / work on your part. I wanted to ask, is that ok with you? 

Although it would be great for folks on non-Microsoft distributed VS Code forks to be able to use the extension as well, I completely understand if you simply don't want to see the extension on the registry and in that case, I will file a report to remove the extension from there.
