### ISSUE TITLE
REST Client adds header to a request without a way to inspect what is added

### ISSUE THREAD

**Issue by AllanXu49** [Huachao/vscode-restclient#874]
I spent several hours today to diagnose an issue until I learned that REST client adds some headers to REST calls without providing any way to inspect what is added.

When a cookie or header is automatically added to a request, REST client needs to provide a way to let us know what exactly is added:

`rest-client.rememberCookiesForSubsequentRequests`
`rest-client.defaultHeaders`

After spending several hours, I used Wireshark and found that my requests are being changed by this extension, without any straightforward way for me  to know what happened.

Postman does not do such a thing. The Console transparently shows the raw version of what has been sent to a server. 

I suggest this matter be addressed.

**Comment by asmith3006** [comment]
Does this help?

Change setting:
"rest-client.previewOption": "exchange"

Then you get (I believe) the full sent request.

**Comment by bohdan-kolomiiets** [comment]
@Huachao , thanks for you work and this extension.

@asmith3006 , thanks for you recommendation, it healped.

But, I would not agree that this recommendation is the solution of root problem.
Other peole still will face this problem, spending some time wondering what is going on, and only then start google the problem.

Doumentation does not specifies that setting `"rest-client.previewOption": "exchange"` shows headers and does not hide any of them.

I use this extensions to debug back-end calls, and cookies are used in many places. Because of this default behavior to save previously set cookies, I have made wrong assumptions about nature of the bug and spent several hours debugging, and onlythen I realized that something wrong with extensions' behavior.

@Huachao , why you decided to make to make option "rest-client.rememberCookiesForSubsequentRequests" default value to be "true". Has any surver been conducted and users voted that they need more browser-like behaviour?

I would propose
1. show all headers send and received (presence of all headers is one of the reasones why people use Fiddler, and your ext.ension too, I suppose).
2. make option "rest-client.rememberCookiesForSubsequentRequests" default value to be "false". It is a well know rule that "explicit is better than implicit".

**Comment by bullhunter7** [comment]
@bohdan-kolomiiets , I agree. adding something to the headers and hiding it from the user would get lots of edorsement.

**Comment by AliMoeen** [comment]
@Huachao 

Would you be able to share your thought on this.

The two headers mentioned in this post can cause serious confusions with high profile API servers such as  `kubernetes` or `Terraform Enterprise`.  I can name many more. Many secured enterprise level products' API absolutely do not like random headers added to the calls. They fail the call with no clear explanation.

If a user decides to get to the bottom of the matter, it takes hours until we find this post.
